### ISSUE TITLE
error during install setup.py

### ISSUE THREAD

**Issue by kydchen** [Convex-Labs/honestnft-shenanigans#36]
Hi guys, when I want to install the setup.py
it shows
error: eth-utils 2.0.0 is installed but eth-utils<2.0.0,>=1.9.5 is required by {'web3'}
but I think my eth-utils is 1.9.5
![image](https://user-images.githubusercontent.com/70866097/150625027-33b37316-0287-493d-a3d3-323791ec190b.png)
what should I do now?
Thank you very much

**Comment by Barabazs** [comment]
Hi @kydchen 
One of the (sub-)dependencies of web3 wants a higher version than web3 needs for eth-utils
My workaround is to install with pip instead of setup.py and you should be able to get around that error.

From the root of the honestnft repo simply do `pip install .`

**Comment by kydchen** [comment]
> Hi @kydchen One of the (sub-)dependencies of web3 wants a higher version than web3 needs for eth-utils My workaround is to install with pip instead of setup.py and you should be able to get around that error.
> 
> From the root of the honestnft repo simply do `pip install .`

I‘ll have a try, thank you very much!

**Comment by Barabazs** [comment]
You're always welcome to join the Discord https://discord.gg/c2wJuzCh

**Comment by arishap1** [comment]
Having a similar issue 
error: eth-utils 1.10.0 is installed but eth-utils<3,>=2.0.0 is required by {'eth-rlp'}

**Comment by Barabazs** [comment]
@ricrosales This can be closed
