### ISSUE TITLE
pulling.py - cannot import name 'chain' from 'utils'

### ISSUE THREAD

**Issue by tradephonic** [Convex-Labs/honestnft-shenanigans#76]
Hi,

I had a bit of a nightmare installing this on my 64bit Windows 10 machine, had to end up installing lots of things individually including Visual C++ and the latest Windows 10 SDK. I am now getting:

ImportError: cannot import name 'chain' from 'utils'

When running pulling.py. I am not sure where to go from here to fix this. Can anyone help?
Thanks

**Comment by Barabazs** [comment]
Hi @tradephonic can you post the output of `pip list` in your terminal and copy the output here?

**Comment by tradephonic** [comment]
@Barabazs Here you go, thanks for getting back to me so quickly:

`Package            Version
------------------ ---------
aiohttp            3.8.1
aiosignal          1.2.0
async-timeout      4.0.2
attrs              21.4.0
base58             2.1.1
bitarray           1.2.2
certifi            2021.10.8
charset-normalizer 2.0.12
cytoolz            0.11.2
eth-abi            2.1.1
eth-account        0.5.7
eth-hash           0.3.2
eth-keyfile        0.5.1
eth-keys           0.3.4
eth-rlp            0.2.1
eth-typing         2.3.0
eth-utils          1.10.0
frozenlist         1.3.0
hexbytes           0.2.2
idna               3.3
ipfs               0.1.0
ipfshttpclient     0.8.0a2
jsonschema         4.4.0
lru-dict           1.1.7
multiaddr          0.0.9
multidict          6.0.2
mypy-extensions    0.4.3
netaddr            0.8.0
numpy              1.22.3
pandas             1.4.2
parsimonious       0.8.1
pip                22.0.4
protobuf           3.20.1
pycryptodome       3.14.1
pyrsistent         0.18.1
python-dateutil    2.8.2
pytz               2022.1
pywin32            303
requests           2.27.1
rlp                2.0.1
setuptools         58.1.0
six                1.16.0
textwrap3          0.9.2
toolz              0.11.2
urllib3            1.26.9
utils              1.0.1
varint             1.0.2
web3               5.29.0
websockets         9.1
wheel              0.37.1
yarl               1.7.2`

**Comment by Barabazs** [comment]
Please try to delete package utils with `pip uninstall utils`. And then try to run the pulling.py command again.

**Comment by tradephonic** [comment]
All working after that. Thanks!
